### ISSUE TITLE
 Twig_Error_Loader  The "/grav/user/plugins/shoppingcart/templates/admin" directory does not exist. 

### ISSUE THREAD

**Issue by jojouser** [flaviocopes/grav-plugin-shoppingcart#1]
Open: /grav/vendor/twig/twig/lib/Twig/Loader/Filesystem.php

         */
        public function addPath($path, $namespace = self::MAIN_NAMESPACE)
        {
            // invalidate the cache
            $this->cache = $this->errorCache = array();
     
            if (!is_dir($path)) {
                throw new Twig_Error_Loader(sprintf('The "%s" directory does not exist.', $path));
            }

**Comment by flaviocopes** [comment]
Fixed! Will release an update now
