### ISSUE TITLE
Add product image preview in the cart

### ISSUE THREAD

**Issue by jjui** [flaviocopes/grav-plugin-shoppingcart#10]
Be able to see product image preview within in the cart, maybe also on checkout summary. 
As products surely will have multiple images, some way to determine main product image would help allot when extending. 

TY

**Comment by jjui** [comment]
[While learning github I refer to my own PR to see some changes. ](https://github.com/jjui/grav-plugin-shoppingcart/pull/1/files)
All missing is actually getting a image ofc, will be interesting to see the proper solution!

**Comment by flaviocopes** [comment]
Added to 1.1, optional, with size option
