### ISSUE TITLE
product variation Support

### ISSUE THREAD

**Issue by jojouser** [flaviocopes/grav-plugin-shoppingcart#13]
Now the plugin don't support product attribute. Will you add support for product attribute, set varying prices based on attributes combinations ? thanks

**Comment by flaviocopes** [comment]
A pro plugin to provide support for product variations/attributes, with stock support, is planned.

**Comment by flaviocopes** [comment]
Provided by https://github.com/flaviocopes/grav-plugin-shoppingcart-product-variations
