### ISSUE TITLE
Repeated id on inputs so label for="x" attribute will not work

### ISSUE THREAD

**Issue by jjui** [flaviocopes/grav-plugin-shoppingcart#15]
At checkout - some inputs is rendered incorrect from the loop. 
The id `id="js__shipping__method"` is repeated on several elements so the `label for="x"` is not working on label click. 

Eg. `input type="checkbox" name="agree_to_terms"` also has the id `id="js__shipping__method"` therefore the label clicks is invalid.

**Comment by flaviocopes** [comment]
Right, thanks for reporting, it was set in the configuration file.

You'll likely need to do this edit to your `user/config/shoppingcart.yaml` file too, if the form was customized: https://github.com/flaviocopes/grav-plugin-shoppingcart/commit/571de8cc2ab12fff4f757ed6907ada586d7c6d2e

**Comment by jjui** [comment]
Nice!
This also relates to [PR made for proper wrapping](https://github.com/flaviocopes/grav-plugin-shoppingcart/pull/16). Im thinking if it is possible to add `outerclasses` to every wrapped label/input? Would be very good, worth to ask.

**Comment by jjui** [comment]
Filed an issue on grav-form regarding `for` attribute as the label click bool is not yet part of the plugin. 
But TY!
