### ISSUE TITLE
Howto set this plugin work with paypal?

### ISSUE THREAD

**Issue by jojouser** [flaviocopes/grav-plugin-shoppingcart#2]
Howto set this plugin work with paypal? thanks

**Comment by flaviocopes** [comment]
Currenty Stripe is the only payment method supported.

In the future a Pro version with additional checkout options and more advanced features will be available, including PayPal.

**Comment by jojouser** [comment]
Can i order or pre-order the Pro version now? How much?

**Comment by flaviocopes** [comment]
Might have news soon, like a free beta program.

**Comment by flaviocopes** [comment]
Have an update for this. There will be a free PayPal add-on out soon.

**Comment by flaviocopes** [comment]
https://github.com/flaviocopes/grav-plugin-shoppingcart-paypal
