### ISSUE TITLE
Shoppingcart buggy as f***

### ISSUE THREAD

**Issue by GodlessGlen** [flaviocopes/grav-plugin-shoppingcart#33]
I tried deleting certain fields from the checkout screen... this led to disastrous results. It broke the payment selection boxes. I then tried to delete the plugin and reinstall it inside the admin panel, and this led to it duplicating numerous other fields. I even deleted the plugin manually over FTP and reinstalled but that has not fixed the issues. It also remembers my previous settings, and it shouldn't. if I delete a plugin the settings I had for it should not be saved. And in the event I reinstall, it should start at the default settings. What in the world is going on?

**Comment by jjui** [comment]
Issue is already noted using Grav _beta 5_ and Shopping Cart _beta 8_, see #32 
What is your versions? 

Your settings and previous settings is set from `user/config` folder and deleted accordingly, also is related to Grav and not Shopping Cart. Pleas make your issue consist specifically of thing related to the plugin.

**Comment by flaviocopes** [comment]
The plugin's settings are stored in `user/config/plugins/shoppingcart.yaml`. It's preserved even if you uninstall. This applies to all Grav plugins and themes. Delete that file, or copy there the default shoppingcart.yaml to use the defaults.

**Comment by flaviocopes** [comment]
As for the specific bug, I have not seen any issue, on Grav 1.1 beta I mean. I assume you're using that? Can you provide a path to recreate the issue? Also attach your `user/config/plugins/shoppingcart.yaml` to help me solve the issue.

**Comment by flaviocopes** [comment]
On it, looks like a configuration merge issue

**Comment by flaviocopes** [comment]
After digging a while, it's a Grav issue. The plugin is probably the first to have such a complicated configuration panel, this is why was never discovered.

Will make a fix in the next release.

**Comment by GodlessGlen** [comment]
Awesome! I really hope that you also give us more flexibility to disable certain checkout fields more easily and know what's going on without it breaking.

**Comment by flaviocopes** [comment]
Sorry it took this much, but made a fix basically by allowing the cart to work without a checkout form at all.

So there will be configuration examples in the documentation, and maybe later some pre-made buttons one can click to generate a standard checkout form in the settings.
