### ISSUE TITLE
type: selectize on countries in blueprint

### ISSUE THREAD

**Issue by jjui** [flaviocopes/grav-plugin-shoppingcart#39]
Realised that the input of `shoppingcart.countries.name` from within plugin bp is using `type: select` - but isn't it better off with `selectize`? Not easy to declare EU in a major list xD

I presume changing this will have no impact on the output, or am I wrong? 
Hey, worth to check!

[https://github.com/flaviocopes/grav-plugin-shoppingcart/blob/develop/blueprints.yaml#L256](https://github.com/flaviocopes/grav-plugin-shoppingcart/blob/develop/blueprints.yaml#L256)

**Comment by jjui** [comment]
Haha, lol, just me being tired.

**Comment by flaviocopes** [comment]
Is it already working like a selectize, right?

**Comment by jjui** [comment]
Yes it does, I was looking in the Countries tab, but maybe allowed/denied countries needs it too?

**Comment by flaviocopes** [comment]
Feel free to change the blueprint 👍

**Comment by jjui** [comment]
Np, just in a site update then ill make the PR 👍
