### ISSUE TITLE
save_order/task:pay ERROR 404

### ISSUE THREAD

**Issue by lsteamgeo** [flaviocopes/grav-plugin-shoppingcart#40]
Hello,

I try to install and configure STRIPE Gateway payment.

My conf : 
- Grav v1.1.1 - Admin v1.1.2
- Shopping Cart v1.1.0-beta.10
- Shopping Cart Stripe Addon  v1.1.0-beta.3

When I try to make a payment with STRIPE, i've an error "Payment not successful. Please contact us."

In firebug I've an 404 Error on this link : 
http://localhost/GRAV/save_order/task:pay 404 Not Found

In URLs Configuration
Checkout URL : /checkout
Save Order URL : /save_order
Visualize Order URL : /order

Can you help me please ?

Thank you

**Comment by jack-webster** [comment]
I have the same issue.

**Comment by flaviocopes** [comment]
Fixed and released an update for the Stripe addon 👍

**Comment by jack-webster** [comment]
Error persists.
