### ISSUE TITLE
Add PayPal option on checkout

### ISSUE THREAD

**Issue by elpollo12** [flaviocopes/grav-plugin-shoppingcart#41]
I'm trying to add PayPal as payment method in the checkout but can not find how to do it from the form. When I click on the "Go and Pay " button performs no action and returns to the checkout . I've already enabled paypal plugin in the Control Panel.

Shopping Cart v1.1.0-beta.8

Shopping Cart PayPal Express Addon v1.1.0-beta.2 test release

I appreciate the help. Thanks.

**Comment by flaviocopes** [comment]
Should now be fixed in Grav 1.1.x
