### ISSUE TITLE
Problems on paypal checkout 

### ISSUE THREAD

**Issue by prinla** [flaviocopes/grav-plugin-shoppingcart#42]
Hello,
I installed the shopcart + paypal payment...
The cart works fine until it comes to checkout...
On the checkout page the "Submit"-Buttons appears 17 times
Clicking one of them first brings up the message "Payment not successful. Please contact us"
After closing the message and clicking the submit-button again it takes me to paypal BUT on a page saying "No token passed".
(As only "Checkout field" I set 1 mandatory field for the name, nothing else... is there a need to put on more?)

**Comment by flaviocopes** [comment]
Just noticed the problem, the default form configuration was broken. Issued a new release to fix it. https://github.com/flaviocopes/grav-plugin-shoppingcart/commit/81ef96f017dd92fb87cad7aea111eaa3f67aef39

**Comment by prinla** [comment]
Just installed your update but still not working...
Indeed now in the checkout it shows the complete form fields...
but still 17 Submit Buttons and still "No token passed" to paypal...
(that seems to be more a problem with your paypal-add-on)

and on top now in the shopping-card (after putting an item in the basket) the small product-image isn't shown anymore...

**Comment by prinla** [comment]
If you wanna test:
http://test12.prinla.com/de/shop

**Comment by prinla** [comment]
I just tried to switch the test-mode off in the paypal-add-on. 
and that removed all form fields from the shopping-cart plugin ?!?

**Comment by prinla** [comment]
After clearing the cache... the form-fields reappeared ?!?

**Comment by flaviocopes** [comment]
Cannot replicate. Make sure you don't have a user/config/plugins/shoppingcart.yaml overriding the configuration.
