### ISSUE TITLE
Problems on paypal checkout part 2

### ISSUE THREAD

**Issue by prinla** [flaviocopes/grav-plugin-shoppingcart#44]
Just installed your update but still not working...
Indeed now in the checkout it shows the complete form fields...
but still 17 Submit Buttons and still "No token passed" to paypal...
(that seems to be more a problem with your paypal-add-on)

and on top now in the shopping-card (after putting an item in the basket) the small product-image isn't shown anymore...

I just tried to switch the test-mode off in the paypal-add-on.
and that removed all form fields from the shopping-cart plugin ?!?

After clearing the cache... the form-fields reappeared ?!?

Each time one changes between test-mode enabled/disabled in the paypal-add-on, the form-fields disappear in the admin-panel of the shoppingcart-plugin...
Only clearing the cache makes them reappear...

If you wanna test:
http://test12.prinla.com/de/shop

**Comment by flaviocopes** [comment]
I think the problem is the configuration was saved to `user/config/plugins/shoppingcart.yaml`, so it's still showing the issue.

Restore it from https://github.com/flaviocopes/grav-plugin-shoppingcart/blob/develop/shoppingcart.yaml
