### ISSUE TITLE
Nan for pricing over 999

### ISSUE THREAD

**Issue by Chiru13** [flaviocopes/grav-plugin-shoppingcart#49]
Hello,

The pricing for over 999 is Nan, please note I DOWNLOADED (1.1.4) the Latest Update and I looked at the release log it said its been fixed in this version: v1.1.0-beta.3 but it hasn't been fixed!

**Comment by carlu93** [comment]
![bug](https://cloud.githubusercontent.com/assets/16781908/24448771/72c8d8ce-1475-11e7-8a66-c32716792801.JPG)
I can confirm this bug. Especially in the cart...
