### ISSUE TITLE
Calculating Taxprice not properly working

### ISSUE THREAD

**Issue by carlu93** [flaviocopes/grav-plugin-shoppingcart#51]
I can't get the Taxprice to be included in the calculation. Although the Country is allowed, the tax doesn't get added to the total price.
If i comment line 210 "if (country.isAllowed)" in shoppingcart_cart.js it gets picked up and calculated.
I attached my shoppingcart.yaml. I think this might be a bug. If you need more information, just tell me.
Thanks a ton!
[shoppingcart.txt](https://github.com/flaviocopes/grav-plugin-shoppingcart/files/880523/shoppingcart.txt)

**Comment by carlu93** [comment]
I got the Subtotal Label by changing Line 520 in shoppingcart_cart.js to:
row += '<td>' + window.PLUGIN_SHOPPINGCART.translations.EXCLUDING_TAXES + '</td>';

**Comment by flaviocopes** [comment]
Can you post a PR with your change?

**Comment by carlu93** [comment]
I don't know if i'm capable to do that. The Change is also only working if taxes are EXCLUDED not included. I came up with the solution by trial and error. I'm currently in my exam phase. After the 8th of April i might have time to look deeper into it and come up with a solution or more info on the problem. sorry :/
