### ISSUE TITLE
Enhancement: If Tax Price is INCLUDED show Tax as extra row in Checkout

### ISSUE THREAD

**Issue by carlu93** [flaviocopes/grav-plugin-shoppingcart#54]
It would be great to have another row in the checkout, which calculates the included tax based on the country setting. Like beneath the subtotal.  Or am I missing something and this is implemented, but not working?
![checkout](https://cloud.githubusercontent.com/assets/16781908/24547514/8517b6ca-1610-11e7-825e-7840d3a1a572.JPG)

**Comment by flaviocopes** [comment]
If tax is included, it's already part of the product price. You would like to show what percentage of the order is tax?

**Comment by carlu93** [comment]
Well the label should show which tax percentage is applied and the TOTAL field should show the amount of tax included in the TOTAL. So if tax is included in the total price there should be another row which shows the included amount of tax. i hope this is understandable.
