### ISSUE TITLE
Empty shipping method select field at checkout

### ISSUE THREAD

**Issue by laprados** [flaviocopes/grav-plugin-shoppingcart#57]
I have a problem with the shipping method select field on checkout. When I have more than one country, the select field is empty. First I thought it was my template or something, but I have the same issue when I make a clean setup with the official shop-skeleton from git.

![screen](https://cloud.githubusercontent.com/assets/26899269/24672605/a4d713ee-1975-11e7-853a-6b8a44c27bca.png)

[shoppingcart.yaml.txt](https://github.com/flaviocopes/grav-plugin-shoppingcart/files/894137/shoppingcart.yaml.txt)

**Comment by gmplab** [comment]
This is not caused by the allowed_countries,
I will report another issue about it.
