### ISSUE TITLE
No token passed

### ISSUE THREAD

**Issue by weput** [flaviocopes/grav-plugin-shoppingcart#59]
Hi.
using the paypal extension i get this issue when trying to checkout.

**Comment by gmplab** [comment]
I also have this problem.

**Comment by gmplab** [comment]
It is caused by wrong total; If your price is not over 999, you can temporary use the older version. 
https://github.com/flaviocopes/grav-plugin-shoppingcart/commit/73112244f13a558142ae5982547af6ad6c1ebf91

**Comment by weput** [comment]
live fersion is working fine.
i disabled the sanbox and send the link to test.. we got money.

**Comment by flaviocopes** [comment]
Is it happening on all browsers, or just one specific browser? Can you try with more than one? 

Also, if it's only happening locally, might be some connection issue, or a local web server problem, if on the server it works fine. Which local web server are you using?

**Comment by bmelim** [comment]
I'm also receiving the error no token passed. 
I setup a test product for the cost of 35, followed through to check out and when it's about to transfer to paypal I get the error. This happens when using sandbox as well as live

**Comment by gmplab** [comment]
You can visit this website  [a quartz cuvette manufacturer](https://www.bsdlab.com)   (I use the latest gravcms and shoppingcart plugin version for this customer.)
To check whether you still have the token error.

**Comment by bmelim** [comment]
Hi @gmplab, I don't have the same issue on your installation.

**Comment by gmplab** [comment]
@bmelim  the only diffrence of my install and offical version is #62 , you can merge it to your local site, then test it again.

**Comment by flaviocopes** [comment]
@bmelim can you paste the product page header? Also, can you try adding a price of 35.00 ?

**Comment by flaviocopes** [comment]
@gmplab going to test the PR today

**Comment by bmelim** [comment]
@flaviocopes sorry for the delay in replying... I have a product for 35.99 - if I add a product with 35.00 which is what I had originally it gave me the same error and shopping cart rounded off my price to 35.

I have just double checked the changes on your commit da3820c from 5 hours ago, and indeed my files are the same as your changes and I still have the same error.

do you need my product page header code? or the URL it goes to at check out?
