### ISSUE TITLE
Switching currency

### ISSUE THREAD

**Issue by mttmccb** [flaviocopes/grav-plugin-shoppingcart#6]
in the shoppingcart_details_item.html.twig and shoppingcart_product_item.html.twig the $ sign is hardcoded, this should use what is set in the YAML.

**Comment by mttmccb** [comment]
Ignore this, I found the line of code and I can see it's been fixed in the version on this repo :)

**Comment by flaviocopes** [comment]
Making a release now :+1:

**Comment by flaviocopes** [comment]
Thanks for reporting!

**Comment by flaviocopes** [comment]
Doing a release now
