### ISSUE TITLE
Cart icon gone after clicking add to cart button

### ISSUE THREAD

**Issue by carlu93** [flaviocopes/grav-plugin-shoppingcart#63]
Just a small issue. After clicking the add to cart button the little font-awesome cart icon is gone. 
the code in question is inside shoppingcart_cart_events.js between line 73 - 99.
I'm not familiar with js or jquery. I did some trial and error, but didn't come up with a solution.
Here's a screenshot: 
![cart](https://cloud.githubusercontent.com/assets/16781908/24830282/f681f30c-1c82-11e7-8cf4-5a57f91c724e.JPG)

**Comment by flaviocopes** [comment]
Thanks for reporting, fixed!
