### ISSUE TITLE
add ability to pay with wire or manually process orders....

### ISSUE THREAD

**Issue by 4evermaat** [flaviocopes/grav-plugin-shoppingcart#8]
Add ability to process orders, such as generate an invoice and bill the person privately to pay (wire transfer, local payment, etc).  But you still capture the requested details via shopping cart checkout.  And then you can either auto-send the payment steps details (which can be customized by user), have them display on a webpage, or both.  When user logs in to check shopping cart, they can see the current status.

webmaster can also have manual approval of invoice for certain items.  Do you support inventory management (keeping track of how many items are sold)?

Also, webmoney and bitcoin payment would be nice.

**Comment by flaviocopes** [comment]
Allowed by the Manual Checkout plugin https://github.com/flaviocopes/grav-plugin-shoppingcart-manual-checkout
