### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by leotiger** [flaviocopes/grav-plugin-shoppingcart#86]
The plugin breaks the security chain for payments. Private keys attached to gateway configurations are exposed on the client side. They should never be exposed there. The plugin injects the shoppingcart configuration settings dynamically into pages related with the shoppingcart.

**Comment by leotiger** [comment]
Could be fixed by defining obligatory split nodes in the config tree of gateway plugins: 

payment.methods.private...
payment.methods.public

This allows to filter and remove the private settings before injection.

**Comment by leotiger** [comment]
Still investigating in which circumstances this happens... the recursive function should filter out private keys but for some reason this is not always true... I will reopen if I have more information.

**Comment by flaviocopes** [comment]
In any case anything related to security shoud be disclosed privately, not publicly, until there is a fix available.

**Comment by leotiger** [comment]
Ok.
